# Generated by Django 5.1.2 on 2024-12-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_type_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
