# Generated by Django 5.1.5 on 2025-01-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_airport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='type',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
